---
# DEFAULT PROFILE

server.port: 9090

spring:
  main:
    banner-mode: "off"
  h2.console.enabled: true
  application.name: operations
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

logging:
  level.org.springframework.web: INFO

---
# TEST PROFILE

spring:
  profiles: test

  jpa.properties.hibernate:
    show_sql: true
    use_sql_comments: true
    format_sql: true

  h2.console.enabled: true